on break of wheat plant or carrot plant or potato plant or beetroot plant:
	
	if event-block is wheat plant:
		if player has permission "remion.autofarm":
			if player has seeds:
				wait 1 tick
				remove 1 seeds from player
				wait 10 ticks
				set block to wheat plant
		if player has permission "remion.additionalplant":
			set {_additionalplant} to random integer between 0 and 2
			drop {_additionalplant} of wheat
