on break of wheat plant or carrot plant or potato plant or beetroot plant:
	if player has permission "remion.autofarm":
		if event-block is wheat plant:
			if player has seeds:
				wait 1 tick
				remove 1 seeds from player
				wait 10 ticks
				set block to wheat plant
				if player has permission "remion.additionalplant":
					set {_additionalplant} to random integer between 0 and 2
					drop {_additionalplant} of wheat
					
		if event-block is carrot plant:
			if player has carrot:
				wait 1 tick
				remove 1 carrot from player
				wait 10 ticks
				set block to carrot plant
				if player has permission "remion.additionalplant":
					set {_additionalplant} to random integer between 0 and 2
					drop {_additionalplant} of carrot
		if event-block is potato plant:
			if player has potato:
				wait 1 tick
				remove 1 potato from player
				wait 10 ticks
				set block to potato plant
				if player has permission "remion.additionalplant":
					set {_additionalplant} to random integer between 0 and 2
					drop {_additionalplant} of potato
		if event-block is beetroot plant:
			if player has beetroot seeds:
				wait 1 tick
				remove 1 beetroot seeds from player
				wait 10 ticks
				set block to beetroot plant
				if player has permission "remion.additionalplant":
					set {_additionalplant} to random integer between 0 and 2
					drop {_additionalplant} of beetroot
